USE [master]
GO

/****** Object:  Database [DB_QuanLyChiTieu]    Script Date: 30/06/2026 11:16:33 ******/
CREATE DATABASE [DB_QuanLyChiTieu] ON  PRIMARY 
( NAME = N'DB_QuanLyChiTieu', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DB_QuanLyChiTieu.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_QuanLyChiTieu_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DB_QuanLyChiTieu_log.LDF' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_QuanLyChiTieu].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET  MULTI_USER 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_QuanLyChiTieu] SET  READ_WRITE 
GO


